### PR TITLE
Add bro's modbus and dnp3 logs to elsa.

### PR DESCRIPTION
**Pull request by tadglines**
This pull request adds bro's modbus and dnp3 logs to elsa. This allows teams monitoring ICS systems to be able to query elsa for modbus and dnp3 specific traffic.

### CODE REVIEW

**Comment by dougburks** [comment]
Thanks for the Pull Request!  I'll take a look as time allows.

**Comment by tadglines** [comment]
It looks like debian/install and debian/postinst also need to be modified. I can do that, but I'm not sure what if the changes to postinst should just be added to the last if case (that includes 1ubuntu0securityonion99) or if if it should be added to a new if case for the next version.

**Comment by dougburks** [comment]
The last if case (that includes 1ubuntu0securityonion99) needs to remain intact.  Changes would need to added to a new if case for the next version.

**Comment by tadglines** [comment]
Ok. If you want, let me know what version to use, and I'll add those changes to the pull request.

**Comment by dougburks** [comment]
I've never liked those long if statements and having to add a new $2 check for every new package.  When I get some time, I'll work out a new strategy.

**Pull request merged**
