### PR TITLE
Added Windows and Cisco VPN ELSA parsing

### PR DESCRIPTION
**Pull request by theflakes**
Windows gets parsed into class 4 and Cisco VPN gets parsed into class 36.  Will be adding more parsers for Cisco logs later in the week; specifically connection teardowns and ACL denies.

### CODE REVIEW

**Comment by dougburks** [comment]
Hi Brian,

Thanks for the pull request!

Can I go ahead and merge today and submit to testers, or are you planning on making any other changes in the near future?

**Comment by theflakes** [comment]
Right now all I’m changing is adding new Event ID specific parsers as I come across event IDs that require more specific parsing to pull the correct SRC IPs and/or usernames out of them.  So I think we can move a head with testing.

I’m sure you are more aware of this than I, but the Windows parsers will need to be placed last in the list so that they don’t parse the SYSMON and Process logs.

There are also Cisco ASA/Pix parsers in the pull request for VPN, conn teardown, and denies.

**Comment by dougburks** [comment]
We actually can't control the order in which separate pattern files are merged into the master pattern file by pdbtool right now:
https://github.com/balabit/syslog-ng/issues/294

Perhaps we need to put all the Windows patterns in the same file so we can control the order?

**Comment by theflakes** [comment]
That would be best then.

Another strange issue is that something is adding spaces before and
after the usernames.  The test messages I have parse the usernames
without spaces in them.  Therefore I am not sure if some logs of the
same type have more spaces around the username than others or is
something after the parsing is adding the spaces.

**Comment by theflakes** [comment]
One other oddity to note is that I added a parser for 6278s yesterday and
they are not parsing in my test even though pdbtool says the parsers are
good.  It looks like the generic parser is parsing them even though the
6278 parsers are listed first in the file.  hmm

All other parsers seem to be working.

**Comment by theflakes** [comment]
I'll combine the files here before lunch unless you have other plans.

**Comment by dougburks** [comment]
@defensivedepth, we can't guarantee the order in which pattern files are merged into the master patterndb.xml:
https://github.com/balabit/syslog-ng/issues/294

So would you be OK with us merging your ELSA patterns for Windows logs into a single pattern file used for all Windows logs obtained from OSSEC agents so that we can control the order of the patterns and ensure proper parsing?

https://github.com/defensivedepth/Win-Process-Tracking_ELSA_Parsers/blob/master/win_process_tracking

https://github.com/defensivedepth/Sysmon_ELSA_Parsers/blob/master/sysmon

**Comment by defensivedepth** [comment]
Yes, no problem.

Side note, I am working on tweaking the Sysmon parser for Sysmonv3....

**Comment by theflakes** [comment]
I've merged them into the "windows" file.  I did not delete the other files.

**Comment by dougburks** [comment]
Thanks, guys!

**Pull request merged**
