### PR TITLE
CISCO parsers

### PR DESCRIPTION
**Pull request by theflakes**
Added two parsers for a couple other Cisco ASA deny logs I have seen a lot of lately.

### CODE REVIEW

**Comment by dougburks** [comment]
Thanks, Brian!

**Comment by theflakes** [comment]
I've looked into creating a default value for the HIPS protocol field but it involves changes to the syslog-ng.conf file.  I don't have time to dig into it as much as needed and am therefore concerned with doing something unintended.  The problem is a minor one I think in that if no protocol is specified by the HIPS log it will default to 0 which is the HOPOPT protocol.  I've gotten good value from the indexing of the HIPS logs when working cases so far.  Therefore I recommend moving forward with this commit if acceptable.  thanks

**Comment by dougburks** [comment]
Hi Brian,

Thanks for the update!

Github is showing "This branch has conflicts that must be resolved".  Can you resolve this or submit a new pull request based on the latest git?

Thanks!

**Comment by theflakes** [comment]
Its not telling me what the conflict is, hmm...

**Pull request closed without merging**
