### PR TITLE
Windows process enhancments

### PR DESCRIPTION
**Pull request by theflakes**
I believe this is ready for testing.  Not seeing any issues in my test VMs so far.

I've tried parsing out hex values, such as the process exit status for 4689 events.  The @NUMBER@ directive says it should do hex with leading 0x's.  But, it isn't working.

Also not completely sure how to best handle renaming "token-elevation" field due to the "-" causing issues in ELSA searches.

### CODE REVIEW

**Comment by dougburks** [comment]
Thanks, Brian!  I'll take a look as time allows.

**Comment by dougburks** [comment]
Hi Brian,

Is this second round of commits ready for merging?

**Comment by theflakes** [comment]
Yes sir.

I did add parsing for Cisco Botnet syslogs as well.  Been on my list
for a while.  Thanks

**Comment by dougburks** [comment]
OK, I'll take a look, thanks!

**Pull request merged**
