### PR TITLE
Sysmon RemoteThread ELSA parsers

### PR DESCRIPTION
**Pull request by strengthnotes**
Doug what are your thoughts on included Sysmon remote thread ELSA parser(s) in a future update ?  I  have been testing the updated version for about a week need a little more testing but think they are close.  These tend to fire when using tools that migrate processes i.e.  meterpreter.  I need to test but we might see the same behavior with malware in the wild.

### CODE REVIEW

**Comment by dougburks** [comment]
Hi James,

This sounds like a great idea!

The next few weeks are going to be very busy for me, so this should give you plenty of time to test and make sure this is a solid solution before I merge.

Thanks!

**Comment by defensivedepth** [comment]
@dougburks FYI, I have this running in PROD just fine....

**Comment by dougburks** [comment]
Thanks @defensivedepth !

**Comment by strengthnotes** [comment]
@defensivedepth just heads up after we talked a couple of weeks ago I went ahead and tweaked these again for 3.10. might need to modify your SQL just a bit.  Let me know if you see any issues or have any problems.

**Comment by defensivedepth** [comment]
@jtaylo78 This morning I tested this updated parser with 3.1 logs and all looks good.

Thanks!

**Pull request merged**
